# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.1 on Thu Feb 21 21:05:26 2019
#

import wx


# begin wxGlade: dependencies
# end wxGlade
# begin wxGlade: extracode
# end wxGlade
class MainFrame(wx.Frame):
	def __init__(self, *args, **kwds):
		# begin wxGlade: MainFrame.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
		wx.Frame.__init__(self, *args, **kwds)
		self.window_1 = wx.SplitterWindow(self, wx.ID_ANY)
		self.window_1_pane_1 = wx.Panel(self.window_1, wx.ID_ANY)
		self.main_class_list = MainClassList(self.window_1_pane_1, wx.ID_ANY)
		self.window_1_pane_2 = wx.Panel(self.window_1, wx.ID_ANY)
		self.text_ctrl_1 = wx.TextCtrl(self.window_1_pane_2, wx.ID_ANY, "just a small test", style=wx.TE_LEFT | wx.TE_MULTILINE)
		
		# Menu Bar
		self.frame_menubar = wx.MenuBar()
		wxglade_tmp_menu = wx.Menu()
		self.frame_menubar.Append(wxglade_tmp_menu, "File")
		self.SetMenuBar(self.frame_menubar)
		# Menu Bar end

		self.__set_properties()
		self.__do_layout()
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: MainFrame.__set_properties
		self.SetTitle("frame")
		self.main_class_list.SetMinSize((500, -1))
		self.window_1.SetMinSize((500, 500))
		self.window_1.SetMinimumPaneSize(20)
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: MainFrame.__do_layout
		sizer_1 = wx.BoxSizer(wx.VERTICAL)
		sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_2.Add(self.main_class_list, 1, wx.EXPAND, 0)
		self.window_1_pane_1.SetSizer(sizer_2)
		sizer_3.Add(self.text_ctrl_1, 0, 0, 0)
		self.window_1_pane_2.SetSizer(sizer_3)
		self.window_1.SplitVertically(self.window_1_pane_1, self.window_1_pane_2)
		sizer_1.Add(self.window_1, 1, wx.EXPAND, 0)
		self.SetSizer(sizer_1)
		sizer_1.Fit(self)
		self.Layout()
		# end wxGlade

# end of class MainFrame
