#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.1 on Thu Feb 21 21:05:26 2019
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from MainFrame import MainFrame


class PyRawEditorUi(wx.App):
	def OnInit(self):
		self.frame = MainFrame(None, wx.ID_ANY, "")
		self.SetTopWindow(self.frame)
		self.frame.Show()
		return True

# end of class PyRawEditorUi

if __name__ == "__main__":
	pyraweditor = PyRawEditorUi(0)
	pyraweditor.MainLoop()
